import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header>
					<nav className="py-8 text-center text-xs">
						<ul className="flex justify-center space-x-4">
							<li>
								<ActiveLink href="/">Homepage</ActiveLink>
							</li>
							<li>
								<ActiveLink href="/products">Products</ActiveLink>
							</li>
						</ul>
					</nav>
				</header>
				<section className="sm:py-18 mx-auto flex w-full max-w-2xl flex-grow flex-col px-8 py-12 sm:px-6 lg:max-w-7xl">
					{children}
				</section>
				<footer className="py-8 text-center text-xs">
					<p>@ 2023</p>
				</footer>
			</body>
		</html>
	);
}
